services:
  db:
    image: postgis/postgis:14-3.4
    restart: 'always'
    ports:
      # PostgreSQL escucha dentro del contenedor siempre en 5432.
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: safe-map
    volumes:
      - ./postgrest:/var/lib/postgresql/data
